### ISSUE TITLE
Access to RTD project + activate PR previews

### ISSUE THREAD

**Issue by consideRatio** [GeorgianaElena/jupyterhub-repo-template#9]
@GeorgianaElena can you provide me with access to https://readthedocs.org/projects/jupyterhub-python-repo-template/? I'd like to activate the PR previews to review #8 and use of sphinx-opengraph to generate previews on discourse.jupyter.org for example.

**Comment by GeorgianaElena** [comment]
@consideRatio, I've just resent the invitation as the previous one had expired. Let me know if you can see it

**Comment by consideRatio** [comment]
Thanks @GeorgianaElena!!
